#!/bin/sh

COMPRESSION="zstd"

[ -n "$1" ] && COMPRESSION="$1"

[ ! -d /mnt/upperdir ] && {
  echo "/mnt/upperdir does not exist. Not persisting changes."
  exit 0
}

if mksquashfs /mnt/upperdir /persist/upperfs-tmp.squashfs -comp "$COMPRESSION" -noappend; then
  mv /persist/upperfs.squashfs /persist/upperfs-backup.squashfs
  mv /persist/upperfs-tmp.squashfs /persist/upperfs.squashfs
fi

